console.log("Hello");
console.log("Hello2");
let a = 5;
try {
    console.log(a);
} catch (error) {
    console.log("An error caught");
}
console.log("Hello3");
console.log("Hello4");